### ISSUE TITLE
Old Firmware_Downloader Version

### ISSUE THREAD

**Issue by Dromopoda** [newracom/nrc7292_sdk#1]
Hi Newracom, I've noticed that the Firmware_Downloader, is outdated...

The commentary does say that the version was updated to a 4.1 28 days from now, but It's not.

I tried clonning the git also downloading the file directly and downloading the sdk .rar.

The .rar has a version 3.0 of the firmware.downloader, and the repository has a version 4.0. 

I'm having issues while erasing XIP F/W Sector, and I saw that the last version (4.1) Upgraded the timeout from 5 to 20; so that could help me and solve my issue.

I await your reply, hope you stay great. Kind regards

**Comment by newracom** [comment]
We updated the last version (4.1) downloader which increased the timeout from 5 sec to 20 sec.
