### ISSUE TITLE
NRC7292 Internal Temperature Sensor Reading

### ISSUE THREAD

**Issue by CrYo-Dyne** [newracom/nrc7292_sdk#16]
Thank you for the detailed SDK and documentation.

I wanted to ask if the NRC7292 SoC includes an internal temperature sensor, and whether this sensor is accessible via the SDK or drivers? This is related to tracking the temperature of the chipset itself.

Please let me know, thank you :)

**Comment by mokajava3** [comment]
The NRC7292 SoC itself does not have an internal temperature sensor. 
However, the NRM7292 module, which incorporates the NRC7292 SoC, includes a temperature sensor that is connected to the module via I2C. 
This allows the NRM7292 module to measure and monitor the temperature using the temperature sensor.
This temperature-based power compensation helps maintain a more stable and reliable wireless connection by adapting the transmit power according to the environmental conditions. 
It ensures that the transmitted signal remains within the desired range and minimizes the impact of temperature fluctuations on the wireless communication.

**Comment by CrYo-Dyne** [comment]
Hi @mokajava3 

Thanks a lot for the feedback, much appreciated. I will close the issue accordingly.
