### ISSUE TITLE
Standalone Mode SPI transaction 512 bytes

### ISSUE THREAD

**Issue by aogonzalez75** [newracom/nrc7292_sdk#2]
Dear All,

I'm using standalone mode to integrate NRC with a microcontroller and I'm having problems to send AT command via SPI with length lower than 512 bytes. The SPI transaction in a Microcontroller is limited to 255 bytes. I don't undertand why needs to send 512 bytes for a simple AT command? Also I don't understand why CRC calculation only included the header?

I will appreciate your support, thanks in advance. Kinds regards

**Comment by newracom** [comment]
Dear @aogonzalez75,

The slot size is defined as 512 bytes at sdk/apps/atcmd/hif.h.
```
/* HSPI */
#define CONFIG_HIF_HSPI_SLOT_NUM		32	/* Don't chagne */
#define CONFIG_HIF_HSPI_SLOT_SIZE		512 /* Don't change */
```
If the SPI transaction is limited as 255 bytes on host MCU, CONFIG_HIF_HSPI_SLOT_SIZE should be 128 and then FW should be rebuilt.
FYI, raspi-atcmd-cli application has hspi_ready() at sdk/apps/atcmd/host/raspi-atcmd-cli/nrc-hspi.c which checks slot number and slot size.
```
static int hspi_ready (hspi_info_t *info)
{
	hspi_regs_t regs;

	if (!HSPI_ACTIVE())
		return -1;

	if (hspi_regs_read_all(&regs) != 0)
		return -1;

	hspi_regs_print_all(&regs);

	if (memcmp(regs.msg, "NRC-HSPI", 8) == 0)
	{
		uint16_t slot_num;
		uint16_t slot_size;
		int que;

		for (que = HSPI_TXQ ; que <= HSPI_RXQ ; que++)
		{
			slot_num = (regs.msg[2 + que] >> 16) & 0xffff;
			slot_size = regs.msg[2 + que] & 0xffff;

			if (slot_num == 0)
				return -1;

			if (slot_size == 0 || slot_size > HSPI_SLOT_SIZE_MAX)
				return -1;

			info->queue.slot[que].num = slot_num;
			info->queue.slot[que].size = slot_size;
		}
...
```
Best regards,
Newracom

**Comment by aogonzalez75** [comment]
we will try to change it. It's not clear for me, why it uses a fixed length on the SPI transaction? why CRC not include the entire message?

**Comment by newracom** [comment]
Dear @aogonzalez75,

Have you tried with the change? If you have any further questions, we'd like to close this issue.
