### ISSUE TITLE
AT-Command AT+WSOFTAP is not working

### ISSUE THREAD

**Issue by GK1234567890** [newracom/nrc7292_sdk#4]
Hi,
I tried to use the latest version of the nrc7292_standalone_xip_ATCMD_UART.bin (ver. 3.1.4 rev.6) with AT-Commands using the AC-CMD Test-Tool v1.3.0 to enter the commands. The command AT+WSOFTAP which configures the module in the AP mode doesn't work. I always get the ERROR 3 as a return message. Other AT-Commands worked successfully. 
After I tried an older Version of the nrc7292_standalone_xip_ATCMD_UART.bin (date: 10-23-2021) the command (AT+WSOFTAP) worked without an error. 
The version with the build date from 10-23-21 works perfect. But we don't know the revision number.
We got that build file from an earlier download.

I am not able to send the binaries into this Forum. If you need the binary, let me know where to push them.
Can you please check the AT Command with the latest version rev 6 and give me a feedback about the issue.
Thank you very much.
Gerrit

![Ver_3 1 4_rev6](https://user-images.githubusercontent.com/104359108/165088348-7dc55fa7-ed4d-46e4-84ed-aa5ed3cbf9a9.PNG)
![Ver_date_10-23-2021](https://user-images.githubusercontent.com/104359108/165088397-e341b90a-c3f7-4f5b-a893-72102227c711.PNG)

**Comment by newracom** [comment]
Dear @GK1234567890,

Thank you for your inquiry and sorry for this inconvenience.
This is the known issue of SoftAP on SDK v1.3.4 rev06 release. 
Please call AT+WBSSMAXIDLE command as below before AT+WSOFTAP.
(ex) AT+WBSSMAXIDLE=10,3
The BSS max idle setting is required for SoftAP on rev06 release.
And this issue will be resolved on the next patch.

Best regards,
Newracom

**Comment by newracom** [comment]
Dear @GK1234567890,

This was resolved already and you could verify with the latest package.
So, I'd like to close this issue.

Best regards,
Newracom
